### ISSUE TITLE
Logined user can access login page!!!

### ISSUE THREAD

**Issue by NastasiaZ** [YSSerious/TrainingCoursesManagementSystem#1]
FIX ASAP!!!

**Comment by FireCrosser** [comment]
It's a feature, not a bug)

**Comment by alexfrankiv** [comment]
@NastasiaZ 
If you're logged in the only way to access login page is to input /login url directly. That's mean that if you do so, you do that intentionally, no misclicks here.
Another thing is that if you re-log in nothing crashes, that's just another opportunity for user to change his role on-the-fly.
That's why i don't think that it's bug.

**Comment by alexfrankiv** [comment]
One more thing
If we deny access to any page when user tries to view it he gets 403 error.
Are you sure that would be okay to give 403 error for admin for example if he intentionally inputs /login url?

**Comment by FireCrosser** [comment]
If admin or any other user tries to access login page, we can redirect him to the home page.

**Comment by alexfrankiv** [comment]
well, we may do so
if @NastasiaZ votes for that

**Comment by alexfrankiv** [comment]
Fixed
